### ISSUE TITLE
Feature: User can sign in

### ISSUE THREAD

**Issue by derrenpamintuan** [derrenpamintuan/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in, sign up, or continue as a guest.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User is able to sign into their account by getting their information from the database, or able to sign up and store their email address and hashed password into the database. The user is also able to continue as a guest in a public account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include the code to generate tables created from the database.
- [x] Update `data.sql` to grab users email and hashed password and store it into the database.

### ☁️ Server Tasks

- [x] Update `server.js` to create a connection to the database.
- [x] Create a post method to let users sign up an account and add it to the database.
- [x] Create a post method to let users sign in to their accounts and grant them a token.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to return a nav bar at the top of the page.
- [x] Create a component to return a form for users to sign in.
- [x] Create a component to return a form for users to sign up.
- [x] Create a component to let users access the home page without signing up.
- [x] Update components to access home page with signing in and having access to the database.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
