### ISSUE TITLE
Feature: User can search for restaurants in surrounding area

### ISSUE THREAD

**Issue by derrenpamintuan** [derrenpamintuan/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for restaurants in surrounding area with input location.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will fill out a form for the location of the search and what they are searching for, returning a list corresponding the that form.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to search for results based on input.
- [x] Create a result page from user form data.
- [x] Update component to display list of results.
- [x] Add error messages for bad requests from user.
- [x] Style result page according to Figma design.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
